version: '3.8'

services:
  web:
    image: nginx:1.25.2-alpine3.18
    ports:
        - "8900:80"
        - "8910:8910"
    volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./public:/app
    restart: always

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: link_generator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - linkme

volumes:
  db_data:

networks:
  linkme:
    external: true