# Stage 1: PHP Application
FROM php:8.3-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    default-mysql-client \
    nginx

# Install PHP extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql sockets

# Copy custom Nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy the production php.ini file to the active configuration file
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

# Ensure the extension directory is correctly set in php.ini
RUN echo "extension_dir=$(php-config --extension-dir)" >> /usr/local/etc/php/php.ini

# Expose ports for the php server
EXPOSE 80 8000 8910