version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:80"

volumes:
  db_data:

networks:
  linkme:
    external: true